# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx2048m
android.nonTransitiveRClass=true
android.nonFinalResIds=false
android.useAndroidX=true
kotlin.code.style=official

# Nettoyage des options obsolètes pour AGP 9.2+
android.defaults.buildfeatures.resvalues=true
android.dependency.useConstraints=true
