package com.example.phoenx.ui.screens.questions

data class Question(
    val id: String,
    val text: String,
    val category: String
)

object QuestionsData {
    val categories = listOf("Enfance", "Famille", "Amour", "Travail", "Valeurs", "Regrets", "Rêves", "Passions", "Sagesse")

    val allQuestions = listOf(
        // ENFANCE
        Question("e1", "Quel est ton premier souvenir d'enfance ?", "Enfance"),
        Question("e2", "Comment était la maison où tu as grandi ?", "Enfance"),
        Question("e3", "Quel enfant étais-tu — calme, turbulent, rêveur ?", "Enfance"),
        Question("e4", "Quel était ton jeu préféré ?", "Enfance"),
        Question("e5", "Qui était ton meilleur ami d'enfance et qu'est-il devenu ?", "Enfance"),
        Question("e6", "Quel repas de ton enfance te manque le plus ?", "Enfance"),
        Question("e7", "Quelle peur d'enfance t'a le plus marqué ?", "Enfance"),
        Question("e8", "Quel était ton rêve de métier quand tu avais 8 ans ?", "Enfance"),
        Question("e9", "Quel professeur t'a le plus influencé et pourquoi ?", "Enfance"),
        Question("e10", "Quel livre ou histoire t'a marqué dans l'enfance ?", "Enfance"),
        Question("e11", "Quel moment d'enfance aurais-tu voulu que tes enfants vivent ?", "Enfance"),
        Question("e12", "Quelle bêtise as-tu faite dont tu es encore un peu fier ?", "Enfance"),
        Question("e13", "Comment s'appelait ton animal de compagnie ?", "Enfance"),
        Question("e14", "Quel objet de ton enfance aimerais-tu avoir gardé ?", "Enfance"),
        Question("e15", "Si tu pouvais parler à l'enfant que tu étais, que lui dirais-tu ?", "Enfance"),

        // FAMILLE
        Question("f1", "Comment décrirais-tu ta relation avec tes parents en un mot ?", "Famille"),
        Question("f2", "Quel sacrifice tes parents ont-ils fait pour toi sans que tu le voies à l'époque ?", "Famille"),
        Question("f3", "Quelle valeur t'a-t-on transmise que tu as transmise à ton tour ?", "Famille"),
        Question("f4", "Quelle valeur t'a-t-on transmise que tu as décidé de ne pas transmettre ?", "Famille"),
        Question("f5", "Quel souvenir avec ta mère revient le plus souvent ?", "Famille"),
        Question("f6", "Quel souvenir avec ton père revient le plus souvent ?", "Famille"),
        Question("f7", "Si tu as des frères et sœurs — quelle est la chose la plus belle que vous ayez faite ensemble ?", "Famille"),
        Question("f8", "Qu'est-ce que ta famille ne sait pas sur toi ?", "Famille"),
        Question("f9", "Quel membre de ta famille t'a le plus surpris dans ta vie ?", "Famille"),
        Question("f10", "Quelle tradition familiale veux-tu que l'on continue après toi ?", "Famille"),
        Question("f11", "Y a-t-il quelque chose que tu n'as jamais dit à un parent décédé ?", "Famille"),
        Question("f12", "Comment ta famille a-t-elle changé ta vision du monde ?", "Famille"),
        Question("f13", "Quel moment en famille était le plus ordinaire mais reste le plus précieux ?", "Famille"),
        Question("f14", "Quelle histoire de tes grands-parents veux-tu absolument que tes proches connaissent ?", "Famille"),
        Question("f15", "Qu'est-ce que ta famille t'a appris sur l'amour ?", "Famille"),

        // AMOUR
        Question("a1", "Comment as-tu su que tu étais amoureux pour la première fois ?", "Amour"),
        Question("a2", "Quelle rencontre a changé le cours de ta vie sentimentale ?", "Amour"),
        Question("a3", "Quelle est la chose la plus courageuse que tu aies faite par amour ?", "Amour"),
        Question("a4", "Quel est le plus beau geste d'amour que quelqu'un ait eu pour toi ?", "Amour"),
        Question("a5", "Qu'est-ce que l'amour t'a appris sur toi-même ?", "Amour"),
        Question("a6", "Y a-t-il quelqu'un à qui tu n'as jamais dit ce que tu ressentais vraiment ?", "Amour"),
        Question("a7", "Quelle relation t'a le plus transformé — positivement ou négativement ?", "Amour"),
        Question("a8", "Qu'est-ce que tu comprends aujourd'hui sur l'amour que tu ne comprenais pas à 20 ans ?", "Amour"),
        Question("a9", "Quel est le plus grand malentendu que tu aies eu avec quelqu'un que tu aimais ?", "Amour"),
        Question("a10", "Si tu pouvais envoyer une lettre à quelqu'un de ton passé amoureux, que dirais-tu ?", "Amour"),
        Question("a11", "Qu'est-ce qui t'a manqué dans certaines relations ?", "Amour"),
        Question("a12", "Qu'est-ce que tu as donné dans l'amour que tu n'aurais pas dû ?", "Amour"),
        Question("a13", "Quelle est ta définition personnelle de l'amour aujourd'hui ?", "Amour"),
        Question("a14", "Quel amour de jeunesse te revient parfois en mémoire ?", "Amour"),
        Question("a15", "Qu'est-ce que tu voudrais que tes proches sachent sur ta vie amoureuse ?", "Amour"),

        // TRAVAIL
        Question("t1", "Quel a été le tournant professionnel le plus décisif de ta vie ?", "Travail"),
        Question("t2", "Quel travail ou mission t'a rendu le plus fier ?", "Travail"),
        Question("t3", "Quel échec professionnel t'a finalement le plus appris ?", "Travail"),
        Question("t4", "Y a-t-il un métier que tu aurais voulu exercer et que tu n'as pas osé ?", "Travail"),
        Question("t5", "Quel collègue ou mentor t'a le plus influencé ?", "Travail"),
        Question("t6", "Qu'est-ce que le travail t'a coûté que tu n'aurais pas dû payer ?", "Travail"),
        Question("t7", "Quel conseil donnerais-tu à quelqu'un qui commence sa carrière ?", "Travail"),
        Question("t8", "Qu'est-ce que tu as accompli dont personne ne connaît l'effort que ça a demandé ?", "Travail"),
        Question("t9", "Y a-t-il un projet que tu aurais aimé finir ?", "Travail"),
        Question("t10", "Qu'est-ce que le travail t'a appris sur les êtres humains ?", "Travail"),
        Question("t11", "Quel moment professionnel aimerais-tu revivre ?", "Travail"),
        Question("t12", "Qu'aurais-tu fait différemment dans ta carrière ?", "Travail"),
        Question("t13", "Quelle décision professionnelle courageuse as-tu prise ?", "Travail"),
        Question("t14", "Comment définirais-tu le succès aujourd'hui, vs à tes débuts ?", "Travail"),
        Question("t15", "Quel héritage professionnel veux-tu laisser ?", "Travail"),

        // VALEURS
        Question("v1", "En quoi crois-tu profondément, même si peu de gens le comprennent ?", "Valeurs"),
        Question("v2", "Quelle est la chose la plus importante dans une vie bien vécue selon toi ?", "Valeurs"),
        Question("v3", "Qu'est-ce que tu défendrais même si cela te coûtait quelque chose ?", "Valeurs"),
        Question("v4", "Ta vision du monde a-t-elle radicalement changé ? Quand et pourquoi ?", "Valeurs"),
        Question("v5", "Qu'est-ce qui te met véritablement en colère dans le monde ?", "Valeurs"),
        Question("v6", "Quelle injustice t'a le plus marqué dans ta vie ?", "Valeurs"),
        Question("v7", "Crois-tu en quelque chose après la mort ? Comment tu l'imagines ?", "Valeurs"),
        Question("v8", "Quelle est ta règle de vie non négociable ?", "Valeurs"),
        Question("v9", "Qu'est-ce que tu as longtemps cru et que tu ne crois plus ?", "Valeurs"),
        Question("v10", "Qu'est-ce que tu as longtemps refusé de croire et que tu acceptes maintenant ?", "Valeurs"),
        Question("v11", "Que penses-tu de la générosité — as-tu été assez généreux dans ta vie ?", "Valeurs"),
        Question("v12", "Quelle est la valeur que tu as le plus du mal à vivre concrètement ?", "Valeurs"),
        Question("v13", "Si tu ne pouvais transmettre qu'une seule valeur, laquelle serait-ce ?", "Valeurs"),
        Question("v14", "Qu'est-ce que tu penses de la vieillesse maintenant que tu la vis ou l'approches ?", "Valeurs"),
        Question("v15", "Que représente pour toi la liberté ?", "Valeurs"),

        // REGRETS
        Question("r1", "Quel est le regret qui revient le plus souvent ?", "Regrets"),
        Question("r2", "Y a-t-il quelqu'un à qui tu dois des excuses que tu n'as pas encore faites ?", "Regrets"),
        Question("r3", "Quelle décision que tu as prise regrettes-tu le plus ?", "Regrets"),
        Question("r4", "Quelle décision que tu n'as pas prise regrettes-tu le plus ?", "Regrets"),
        Question("r5", "Y a-t-il une relation que tu aurais pu sauver et que tu n'as pas sauvée ?", "Regrets"),
        Question("r6", "Qu'est-ce que tu t'es interdit et que tu aurais dû t'autoriser ?", "Regrets"),
        Question("r7", "Qu'est-ce que tu as fait par peur et que tu aurais voulu faire par choix ?", "Regrets"),
        Question("r8", "Y a-t-il quelque chose que tu voudrais que quelqu'un te pardonne ?", "Regrets"),
        Question("r9", "Qu'aurais-tu voulu qu'on te dise avant qu'il soit trop tard ?", "Regrets"),
        Question("r10", "Quel regret est-il encore temps de réparer ?", "Regrets"),
        Question("r11", "Qu'est-ce que tu aurais voulu vivre et que tu n'as pas vécu ?", "Regrets"),
        Question("r12", "Y a-t-il quelqu'un que tu as perdu de vue et que tu penses encore ?", "Regrets"),
        Question("r13", "Quelle version de toi-même as-tu abandonnée en chemin et est-ce que tu le regrettes ?", "Regrets"),
        Question("r14", "Qu'est-ce que tu aurais voulu dire à quelqu'un qui est décédé ?", "Regrets"),
        Question("r15", "Si tu pouvais changer une seule chose dans ta vie, laquelle serait-ce ?", "Regrets"),

        // RÊVES
        Question("rv1", "Quel voyage a été le plus transformateur de ta vie ?", "Rêves"),
        Question("rv2", "Quel lieu dans le monde t'a fait ressentir quelque chose d'unique ?", "Rêves"),
        Question("rv3", "Quelle œuvre d'art (film, livre, musique, tableau) t'a changé ?", "Rêves"),
        Question("rv4", "Quelle passion as-tu eue dont peu de gens sont au courant ?", "Rêves"),
        Question("rv5", "Y a-t-il un rêve que tu n'as jamais réalisé et qui reste vivant en toi ?", "Rêves"),
        Question("rv6", "Quel voyage rêvais-tu de faire et n'as jamais fait ?", "Rêves"),
        Question("rv7", "Quelle aventure as-tu vécue dont tu es particulièrement fier ?", "Rêves"),
        Question("rv8", "Qu'est-ce qui te rend encore émerveillé aujourd'hui ?", "Rêves"),
        Question("rv9", "Quelle musique ou chanson raconte le mieux ta vie ?", "Rêves"),
        Question("rv10", "Quel film ou livre t'a donné l'impression qu'il avait été fait pour toi ?", "Rêves"),

        // PASSIONS & HOBBIES
        Question("ph1", "Quelle activité te fait perdre la notion du temps ?", "Passions"),
        Question("ph2", "Quel sport a marqué ta vie, en tant que pratiquant ou spectateur ?", "Passions"),
        Question("ph3", "As-tu une collection secrète ou une passion dont tu parles peu ?", "Passions"),
        Question("ph4", "Quel est l'objet le plus précieux que tu possèdes par passion ?", "Passions"),
        Question("ph5", "Quelle discipline aurais-tu aimé maîtriser (musique, dessin, sport...) ?", "Passions"),
        Question("ph6", "Quel est ton rapport à la nature et aux grands espaces ?", "Passions"),
        Question("ph7", "Y a-t-il un domaine où tu te considères comme un expert ?", "Passions"),
        Question("ph8", "Quelle est la plus belle émotion que le sport t'a procurée ?", "Passions"),
        Question("ph9", "Aimes-tu cuisiner ? Quel est ton plat signature ?", "Passions"),
        Question("ph10", "Quel est ton passe-temps favori le dimanche après-midi ?", "Passions"),
        Question("ph11", "As-tu déjà fait un voyage uniquement pour une passion ?", "Passions"),
        Question("ph12", "Quel instrument de musique te touche le plus ?", "Passions"),
        Question("ph13", "Es-tu plutôt manuel ou intellectuel dans tes loisirs ?", "Passions"),
        Question("ph14", "Quel défi physique ou artistique es-tu fier d'avoir relevé ?", "Passions"),
        Question("ph15", "Si tu avais tout le temps du monde, quel nouveau hobby lancerais-tu ?", "Passions"),

        // SAGESSE
        Question("s1", "Qu'est-ce que tu sais à 50 ans que tu aurais voulu savoir à 25 ans ?", "Sagesse"),
        Question("s2", "Quel conseil t'a-t-on donné que tu n'as pas suivi et que tu aurais dû suivre ?", "Sagesse"),
        Question("s3", "Quel conseil t'a-t-on donné que tu n'as pas suivi et tu as bien fait ?", "Sagesse"),
        Question("s4", "Qu'est-ce que la maladie, la perte ou la souffrance t'a appris ?", "Sagesse"),
        Question("s5", "Qu'est-ce que tu as compris sur l'amitié en vieillissant ?", "Sagesse"),
        Question("s6", "Qu'est-ce que l'argent t'a appris ?", "Sagesse"),
        Question("s7", "Qu'est-ce que tu aurais voulu qu'on t'apprenne à l'école ?", "Sagesse"),
        Question("s8", "Quelle est la chose la plus simple qui te rend heureux ?", "Sagesse"),
        Question("s9", "Qu'est-ce que tu fais différemment aujourd'hui qu'il y a 20 ans ?", "Sagesse"),
        Question("s10", "Quelle est la leçon que tu as dû apprendre plusieurs fois avant de vraiment la comprendre ?", "Sagesse"),
        Question("s11", "Qu'est-ce que tu penses de la mort maintenant ?", "Sagesse"),
        Question("s12", "Qu'est-ce que tu veux qu'on retienne de toi ?", "Sagesse"),
        Question("s13", "Si tu pouvais revivre une seule journée de ta vie, laquelle serait-ce ?", "Sagesse"),
        Question("s14", "Qu'est-ce que tu veux que tes enfants ou proches sachent sur qui tu étais vraiment ?", "Sagesse"),
        Question("s15", "Quelle est la chose dont tu es le plus fier dans ta vie ?", "Sagesse"),
        Question("s16", "Qu'est-ce que tu as fait qui comptait vraiment pour les autres sans que tu le saches ?", "Sagesse"),
        Question("s17", "Quel est le plus beau cadeau que la vie t'ait fait ?", "Sagesse"),
        Question("s18", "Qu'est-ce que tu ferais demain si tu savais que c'est ton dernier jour ?", "Sagesse"),
        Question("s19", "Que dirais-tu à tes proches s'ils pouvaient t'entendre une dernière fois ?", "Sagesse"),
        Question("s20", "Qu'est-ce qui fait que ta vie a eu du sens ?", "Sagesse")
    )
}
