package com.example.phoenx.ui.screens.detective

data class InspirationCategory(
    val title: String,
    val emoji: String,
    val questions: List<String>
)

object InspirationData {
    val categories = listOf(
        InspirationCategory("Souvenirs d'Enfance", "🏠", listOf(
            "Comment s'appelait mon école primaire ?",
            "Quel était le prénom de mon instituteur(trice) préféré(e) ?",
            "Dans quelle rue ai-je grandi ?",
            "Quel était le nom de mon meilleur ami d'enfance ?",
            "Quelle était ma couleur préférée à 10 ans ?",
            "Quel jouet ne voulais-je jamais prêter ?",
            "Quel était mon dessin animé préféré ?",
            "Comment s'appelait mon animal de compagnie d'enfance ?",
            "Quelle était ma matière scolaire préférée ?",
            "Quel sport pratiquais-je à l'école ?",
            "Quelle était la punition que je redoutais le plus ?",
            "Quel était mon plat préféré que ma mère cuisinait ?",
            "Quel était le prénom de mon voisin(e) d'enfance ?",
            "Quelle était la marque de mon premier vélo ?",
            "Quel était le surnom que mes parents me donnaient ?",
            "Dans quelle ville passais-je mes vacances d'été ?",
            "Quel était mon livre préféré avant 12 ans ?",
            "Quelle bêtise ai-je faite dont je ne t'ai jamais parlé ?",
            "Quel était le jeu de société que j'adorais ?",
            "Quelle chanson me faisait toujours danser enfant ?"
        )),
        InspirationCategory("Notre Histoire", "💕", listOf(
            "Dans quelle ville nous sommes-nous rencontrés ?",
            "Quelle était la première chose que tu m'as dite ?",
            "Quel était le nom de l'endroit de notre première sortie ?",
            "Quelle chanson était devenue 'notre' chanson ?",
            "Quel était le premier cadeau que je t'ai offert ?",
            "Dans quel restaurant avons-nous dîné pour la première fois ?",
            "Quelle était ma phrase favorite quand j'étais de bonne humeur ?",
            "Quel surnom t'avais-je donné que personne d'autre ne connaît ?",
            "Quelle bêtise avons-nous faite ensemble sans jamais le dire ?",
            "Quel était notre film qu'on regardait en boucle ?",
            "Quelle expression secrète nous seuls comprenions ?",
            "Dans quelle ville avons-nous passé notre premier voyage ?",
            "Quel était le premier plat que j'ai cuisiné pour toi ?",
            "Quelle dispute avons-nous eue dont tu te souviens encore ?",
            "Quel était mon rituel du matin que tu trouvais bizarre ?",
            "Quelle promesse t'avais-je faite en premier ?",
            "Quel moment t'a montré que tu pouvais me faire confiance ?",
            "Quelle était ma façon unique de te dire que je t'aimais ?",
            "Quel objet m'avais-tu offert que j'ai gardé précieusement ?",
            "Quelle est la chose la plus folle qu'on ait faite ensemble ?"
        )),
        InspirationCategory("Lieux et Voyages", "✈️", listOf(
            "Quel est le premier pays étranger que j'ai visité ?",
            "Dans quelle ville me suis-je senti(e) le plus chez moi ?",
            "Quel était le nom de l'hôtel de notre voyage mémorable ?",
            "Quelle ville aurais-je voulu habiter toute ma vie ?",
            "Dans quel pays ai-je mangé le meilleur repas de ma vie ?",
            "Quelle montagne ou quel sommet ai-je gravi ?",
            "Quel était le nom de la plage où j'allais chaque été ?",
            "Dans quelle ville ai-je vécu le plus longtemps ?",
            "Quel pays m'a le plus transformé(e) ?",
            "Quel endroit m'a rendu(e) vraiment heureux/heureuse ?",
            "Quelle ville européenne ai-je visitée avec toi ?",
            "Dans quel quartier aimais-je me perdre ?",
            "Quel voyage ai-je fait seul(e) dont je t'ai peu parlé ?",
            "Quel était le nom du camping où j'allais enfant ?",
            "Quelle capitale mondiale n'avais-je jamais visitée ?",
            "Où me serais-je installé(e) si j'avais pu ?",
            "Quel chemin prenais-je pour me ressourcer ?",
            "Quel musée m'a profondément marqué(e) ?",
            "Quelle île aurais-je voulu habiter ?",
            "Dans quelle ville ai-je pleuré de bonheur en arrivant ?"
        )),
        InspirationCategory("Goûts et Passions", "🎭", listOf(
            "Quel plat mangeais-je en secret ?",
            "Quelle musique écoutais-je quand j'étais seul(e) ?",
            "Quel film regardais-je sans jamais l'assumer ?",
            "Quelle activité pratiquais-je sans en parler ?",
            "Quel livre avais-je lu plus de trois fois ?",
            "Quel artiste admirais-je en secret ?",
            "Quelle émission ne ratais-je jamais ?",
            "Quel sport regardais-je avec passion ?",
            "Quel aliment n'aimais-je absolument pas ?",
            "Quelle couleur ne portais-je jamais ?",
            "Quel instrument aurais-je voulu jouer ?",
            "Quelle cuisine étrangère était ma préférée ?",
            "Quel hobby avais-je abandonné et regrettais ?",
            "Quelle chanson me faisait pleurer sans raison ?",
            "Quel parfum me rendait nostalgique ?",
            "Quel genre de films me faisait toujours pleurer ?",
            "Quelle boisson prenais-je le matin ?",
            "Quel était mon péché mignon culinaire ?",
            "Quelle saison préférais-je et pourquoi ?",
            "Quel paysage me coupait le souffle ?"
        )),
        InspirationCategory("Habitudes et Détails", "🔍", listOf(
            "Quelle phrase répétais-je sans m'en rendre compte ?",
            "Quel était mon tic gestuel le plus reconnaissable ?",
            "À quelle heure me levais-je le weekend ?",
            "Quel était mon rituel avant de dormir ?",
            "Comment savais-tu que j'étais de mauvaise humeur ?",
            "Quelle était ma façon unique de rire ?",
            "Quel objet cherchais-je toujours et ne trouvais pas ?",
            "Comment rangeais-je (ou ne rangeais-je pas) mes affaires ?",
            "Quelle était ma position préférée pour lire ?",
            "Quel était mon côté du lit ?",
            "Quelle était la première chose que je faisais en rentrant ?",
            "Quelle était la dernière chose avant de sortir ?",
            "Comment prenais-je mon café ou mon thé ?",
            "Comment me consolais-je quand j'étais triste ?",
            "Quel était mon mot favori trop souvent utilisé ?",
            "Comment montrais-je ma fierté sans le dire ?",
            "Comment t'appelais-je quand j'étais en colère ?",
            "Quel était mon geste affectueux le plus reconnaissable ?",
            "Quelle application utilisais-je le plus ?",
            "Quel était mon moyen de transport préféré ?"
        )),
        InspirationCategory("Moments Difficiles", "🤝", listOf(
            "Quel moment difficile avons-nous traversé ensemble ?",
            "Comment t'ai-je soutenu(e) pendant ta pire période ?",
            "Quelle dispute n'avons-nous jamais vraiment réglée ?",
            "Quel secret as-tu gardé pour moi ?",
            "Quelle décision difficile ai-je prise dont tu savais ?",
            "Comment m'appelais-tu quand tu voulais que je me calme ?",
            "Quelle peur avons-nous surmontée ensemble ?",
            "Quel moment de ma vie t'a demandé le plus de patience ?",
            "Quelle mauvaise nouvelle avons-nous apprise ensemble ?",
            "Comment montrais-je que j'avais besoin d'aide ?",
            "Quel surnom me donnais-tu quand j'étais vulnérable ?",
            "Quelle épreuve m'a rendu(e) plus fort(e) ?",
            "Quel était le signe que quelque chose n'allait pas ?",
            "Quelle nuit difficile avons-nous passée ensemble ?",
            "Comment te remerciais-je sans vraiment le dire ?",
            "Quel moment de crise as-tu géré pour moi ?",
            "Quelle erreur ai-je faite que tu m'as aidé(e) à surmonter ?",
            "Quel était notre code secret quand ça n'allait pas ?",
            "Quelle période t'a le plus inquiété(e) pour moi ?",
            "Comment t'exprimais-je ma gratitude sans mots ?"
        )),
        InspirationCategory("Rêves et Projets", "🌟", listOf(
            "Quel métier aurais-je voulu exercer si j'avais osé ?",
            "Quel pays aurais-je voulu habiter un an ?",
            "Quel instrument aurais-je voulu apprendre ?",
            "Quel projet avions-nous évoqué et jamais réalisé ?",
            "Quelle langue aurais-je voulu parler couramment ?",
            "Quel sport extrême aurais-je voulu pratiquer ?",
            "Quel livre aurais-je voulu écrire ?",
            "Quelle invention aurais-je voulu créer ?",
            "Quelle cause aurais-je voulu défendre ?",
            "Quel voyage de rêve n'ai-je jamais pu faire ?",
            "Quelle maison aurais-je voulu construire ?",
            "Quel animal aurais-je voulu adopter ?",
            "Quelle formation aurais-je voulu suivre plus tôt ?",
            "Quel défi personnel aurais-je voulu accomplir ?",
            "Quelle rencontre aurais-je voulu avoir ?",
            "Quel restaurant aurais-je voulu ouvrir ?",
            "Quel film aurais-je voulu créer ?",
            "Quelle association aurais-je voulu fonder ?",
            "Quel endroit aurais-je voulu transformer en résidence ?",
            "Quel rêve d'enfant n'ai-je jamais abandonné ?"
        )),
        InspirationCategory("Ce Que Je Disais Toujours", "💬", listOf(
            "Quelle citation répétais-je souvent ?",
            "Quel conseil donnais-je systématiquement ?",
            "Quelle leçon de vie revenait dans mes conversations ?",
            "Quelle blague faisais-je tout le temps ?",
            "Quelle expression utilisais-je pour encourager ?",
            "Que disais-je avant une décision importante ?",
            "Quelle était ma façon de commencer une histoire ?",
            "Que disais-je quand quelque chose m'énervait ?",
            "Quelle phrase prononçais-je quand j'étais heureux/heureuse ?",
            "Que répétais-je sur l'amour ou l'amitié ?",
            "Comment concluais-je une conversation importante ?",
            "Que disais-je avant de partir en voyage ?",
            "Quelle mise en garde donnais-je aux gens que j'aimais ?",
            "Que disais-je quand quelqu'un me remerciait ?",
            "Quelle phrase utilisais-je pour clore un désaccord ?",
            "Que disais-je en regardant le ciel ou la nature ?",
            "Quelle expression t'agaçait parce que je la répétais ?",
            "Que disais-je en regardant des photos de ma jeunesse ?",
            "Quelle phrase prononçais-je quand quelque chose me touchait ?",
            "Que disais-je le soir avant de dormir ?"
        )),
        InspirationCategory("Personnes Importantes", "👥", listOf(
            "Comment sappelait mon meilleur(e) ami(e) d'adolescence ?",
            "Quel était le prénom de mon mentor professionnel ?",
            "Comment s'appelait la personne qui m'a donné ma première chance ?",
            "Quel était le prénom de mon voisin(e) le plus proche ?",
            "Comment s'appelait le médecin qui m'a suivi des années ?",
            "Quel était le prénom de la personne aimée avant toi ?",
            "Comment s'appelait mon professeur le plus influent ?",
            "Quel était le prénom de mon collègue le plus fidèle ?",
            "Comment s'appelait la personne à qui je dois le plus ?",
            "Quel était le prénom de l'ami(e) perdu(e) de vue ?",
            "Comment s'appelait la personne qui m'a le plus blessé(e) ?",
            "Quel était le prénom de celui/celle qui m'a appris à conduire ?",
            "Comment s'appelait mon entraîneur sportif ?",
            "Quel était le prénom de mon associé principal ?",
            "Comment s'appelait la personne qui m'a appris à cuisiner ?",
            "Quel était le prénom de mon confident(e) absolu(e) ?",
            "Comment s'appelait la personne dont j'admirais le courage ?",
            "Quel était le prénom de celui/celle qui m'a aidé dans ma pire période ?",
            "Comment s'appelait la personne à qui je n'ai jamais dit merci ?",
            "Quel était le prénom de la personne qui me connaissait mieux que quiconque ?"
        )),
        InspirationCategory("Questions Profondes", "🔮", listOf(
            "Quelle chose me faisait le plus peur et que peu savaient ?",
            "Quel secret ai-je gardé toute ma vie ?",
            "Quelle décision regrettais-je sans jamais l'avouer ?",
            "Quel talent cachais-je dont tu étais l'un des rares à savoir ?",
            "Quelle vérité sur moi-même ai-je mis des années à accepter ?",
            "Quel était mon plus grand complexe jamais montré ?",
            "Quelle croyance guidait toutes mes décisions ?",
            "Quel moment m'a donné le plus de doutes ?",
            "Quelle erreur de jeunesse m'a suivi longtemps ?",
            "Quelle conversation aurais-je voulu avoir ?",
            "Quel acte de générosité ai-je fait sans en parler ?",
            "Quelle injustice m'a marqué(e) à jamais ?",
            "Quel était mon rêve le plus intime ?",
            "Quelle partie de moi ai-je sacrifiée pour les autres ?",
            "Quel moment m'a rendu(e) le plus vulnérable ?",
            "Quelle rencontre a tout changé dans ma façon de voir ?",
            "Quel poids portais-je seul(e) depuis des années ?",
            "Quelle vérité ai-je comprise trop tard ?",
            "Qu'aurais-je voulu que les gens sachent de moi ?",
            "Si tu ne devais garder qu'un souvenir de moi, lequel ?"
        ))
    )
}
